Repository wibsonorg/buyer-sdk, pull requests merged in 2018-10, with the labels that each got.

#53 Slack Notification logger
  buyer-api/.env.example
  buyer-api/config/index.js
  buyer-api/package-lock.json
  buyer-api/package.json
  buyer-api/src/utils/logger.js
Labels: wallet parallelization

#51 Check parent balance before starting the Buyer API service
  buyer-api/.env.example
  buyer-api/config/index.js
  buyer-api/src/server.js
  buyer-api/src/utils/funding.js
  buyer-api/src/utils/index.js
Labels: wallet parallelization

#50 Fund Buyer's children accounts
  buyer-api/src/app.js
  buyer-api/src/facades/index.js
  buyer-api/src/facades/transferFacade.js
  buyer-api/src/queues/createQueue.js
  buyer-api/src/queues/fundingQueue.js
  buyer-api/src/queues/index.js
  buyer-api/src/queues/workers/checkStatus.js
  buyer-api/src/queues/workers/sendFunds.js
  buyer-api/src/queues/workers/transferETH.js
  buyer-api/src/queues/workers/transferWIB.js
  buyer-api/src/services/signingService.js
  buyer-api/test/facades/transferFacadeSpec.js
  buyer-api/test/setup.js
  buyer-signing-service/.env.example
  buyer-signing-service/config/index.js
  buyer-signing-service/scripts/test.sh
  buyer-signing-service/src/app.js
  buyer-signing-service/src/facades/sign/transferETHFacade.js
  buyer-signing-service/src/facades/sign/transferWIBFacade.js
  buyer-signing-service/src/helpers/accounts.js
  buyer-signing-service/src/middlewares/fourOhFourHandler.js
  buyer-signing-service/src/middlewares/index.js
  buyer-signing-service/src/routes/sign/index.js
  buyer-signing-service/src/routes/sign/transfer.js
  buyer-signing-service/src/utils/wibson-lib/contracts/signTransaction.js
  buyer-signing-service/test/facades/sign/newOrderFacadeSpec.js
  buyer-signing-service/test/routes/sign/addNotaryToOrderSpec.js
  buyer-signing-service/test/routes/sign/closeOrderSpec.js
  buyer-signing-service/test/routes/sign/newOrderSpec.js
  buyer-signing-service/test/routes/sign/transfer.js
  buyer-signing-service/test/setup.js
Labels: wallet parallelization

#52 Batch queue + Consolidate responses
  buyer-api/package.json
  buyer-api/src/app.js
  buyer-api/src/facades/createDataOrderFacade.js
  buyer-api/src/facades/getBatchesFacade.js
  buyer-api/src/facades/index.js
  buyer-api/src/queues/createDataOrderQueue.js
  buyer-api/src/routes/dataOrders/batches.js
  buyer-api/src/routes/dataOrders/createDataOrder.js
  buyer-api/src/routes/dataOrders/index.js
  buyer-api/src/services/batchInfo.js
Labels: wallet parallelization

#57 Funding monitor
  buyer-api/.env.example
  buyer-api/.gitignore
  buyer-api/config/index.js
  buyer-api/src/facades/index.js
  buyer-api/src/facades/transferFacade.js
  buyer-api/src/queues/fundingQueue.js
  buyer-api/src/queues/workers/sendFunds.js
  buyer-api/src/queues/workers/transferETH.js
  buyer-api/src/queues/workers/transferWIB.js
  buyer-api/src/server.js
  buyer-api/src/utils/funding.js
  buyer-api/src/utils/index.js
Labels: wallet parallelization

#54 Collect account funding metrics
  buyer-api/src/app.js
  buyer-api/src/facades/metricsFacade.js
  buyer-api/src/queues/workers/checkStatus.js
  buyer-api/src/queues/workers/transferETH.js
  buyer-api/src/queues/workers/transferWIB.js
  buyer-api/src/routes/index.js
  buyer-api/src/routes/metrics.js
  buyer-api/src/utils/storage.js
Labels: wallet parallelization

#61 Consolidating data responses and boughts on each bucket
  buyer-api/src/facades/getBatchesFacade.js
  buyer-api/src/routes/dataOrders/createDataOrder.js
  buyer-api/src/services/batchInfo.js
Labels: wallet parallelization

#62 Fix Wibson Token formatting
  buyer-api/src/routes/account.js
  buyer-api/src/utils/index.js
  buyer-api/src/utils/wibson-lib/coin/index.js
  buyer-api/test/facades/addNotariesToOrderFacadeSpec.js
  buyer-api/test/facades/createDataOrderFacadeSpec.js
  buyer-api/test/facades/transferFacadeSpec.js
  buyer-api/test/routes/dataOrders/addNotariesToOrderSpec.js
  buyer-api/test/routes/dataOrders/createDataOrderSpec.js
  buyer-api/test/routes/health_spec.js
  buyer-api/test/setup.js
Labels: wallet parallelization

#68 Merge transfer funds workers into one
  buyer-api/src/facades/transferFacade.js
  buyer-api/src/queues/fundingQueue.js
  buyer-api/src/queues/workers/transferETH.js
  buyer-api/src/queues/workers/transferFunds.js
  buyer-api/src/queues/workers/transferWIB.js
Labels: wallet parallelization, wip

#67 Close batches
  buyer-api/src/app.js
  buyer-api/src/facades/addNotariesToOrderFacade.js
  buyer-api/src/facades/closeBatchFacade.js
  buyer-api/src/facades/closeDataOrderFacade.js
  buyer-api/src/facades/getBatchesFacade.js
  buyer-api/src/facades/getOrdersFacade.js
  buyer-api/src/facades/index.js
  buyer-api/src/queues/closeDataOrderQueue.js
  buyer-api/src/queues/index.js
  buyer-api/src/routes/dataOrders/closeDataOrder.js
  buyer-api/src/routes/dataOrders/createDataOrder.js
  buyer-api/src/services/batchInfo.js
Labels: wallet parallelization

#80 Update buy data flow
  buyer-api/src/app.js
  buyer-api/src/contractEventSubscribers/buyDataSubscriber.js
  buyer-api/src/contractEventSubscribers/cacheUpdaterSubscriber.js
  buyer-api/src/contractEventSubscribers/index.js
  buyer-api/src/facades/dataResponseFacade/addDataResponse.js
  buyer-api/src/facades/dataResponseFacade/closeDataResponse.js
  buyer-api/src/facades/dataResponseFacade/index.js
  buyer-api/src/facades/helpers/performTransaction.js
  buyer-api/src/facades/index.js
  buyer-api/src/queues/createDataResponseQueue.js
  buyer-api/src/queues/dataResponseQueue.js
  buyer-api/src/queues/index.js
  buyer-api/src/queues/transactionQueue.js
  buyer-api/src/utils/stores.js
Labels: sequential txs

#83 Update Close DataOrder flow
  buyer-api/src/facades/closeDataOrderFacade.js
Labels: sequential txs

#82 Update Increase Approval flow
  buyer-api/src/facades/dataResponseFacade/increaseApproval.js
  buyer-api/src/facades/dataResponseFacade/index.js
  buyer-api/src/facades/index.js
  buyer-api/src/queues/balanceQueue.js
  buyer-api/src/queues/index.js
Labels: sequential txs
