Repository wibsonorg/buyer-sdk, pull requests merged in 2019-02, with the labels that each got.

#119 Allow the Buyer API to receive DataResponses from sellers
  buyer-api/.env.example
  buyer-api/config/index.js
  buyer-api/src/app.js
  buyer-api/src/facades/dataResponseFacade/addDataResponse.js
  buyer-api/src/facades/dataResponseFacade/closeDataResponse.js
  buyer-api/src/facades/dataResponseFacade/increaseApproval.js
  buyer-api/src/facades/dataResponseFacade/index.js
  buyer-api/src/facades/index.js
  buyer-api/src/operations/addDataResponse.js
  buyer-api/src/queues/dataResponseQueue.js
  buyer-api/src/queues/index.js
  buyer-api/src/routes/dataOrders/addDataResponse.js
  buyer-api/src/routes/dataOrders/index.js
  buyer-api/src/routes/dataOrders/middlewares/fetchDataOrder.js
  buyer-api/src/server.js
  buyer-api/src/utils/contracts.js
  buyer-api/src/utils/storage.js
  buyer-api/src/utils/stores.js
  buyer-api/src/utils/wibson-lib/s3/index.js
  buyer-api/test/operations/addDataResponse.mock.js
  buyer-api/test/operations/addDataResponse.test.js
  buyer-api/test/operations/snapshots/addDataResponse.test.js.md
  buyer-api/test/operations/snapshots/addDataResponse.test.js.snap
  buyer-api/test/queues/transactionQueue.test.js
  buyer-api/test/routes/dataOrders/middlewares/fetchDataOrder.mock.js
  buyer-api/test/routes/dataOrders/middlewares/fetchDataOrder.test.js
  buyer-api/test/setup.js
Labels: enhancement, v2.0

#122 v2 get data order tests
  buyer-api/package-lock.json
  buyer-api/package.json
  buyer-api/scripts/test.sh
  buyer-api/src/contractEvents/dataOrderSubscriber.js
  buyer-api/src/contractEvents/listenContractEvents.js
  buyer-api/src/contractEvents/notarySubscriber.js
  buyer-api/src/operations/createDataOrder.js
  buyer-api/src/routes/buyerInfos.js
  buyer-api/src/routes/dataOrders/createDataOrder.js
  buyer-api/src/routes/dataOrders/getDataOrder.js
  buyer-api/src/utils/blockchain.js
  buyer-api/src/utils/storage.js
  buyer-api/src/utils/stores.js
  buyer-api/test/contractEvents/dataOrderSubscriber.mock.js
  buyer-api/test/contractEvents/dataOrderSubscriber.test.js
  buyer-api/test/facades/closeDataOrderFacade.test.js
  buyer-api/test/helpers.js
  buyer-api/test/queues/transactionQueue.test.ignore.js
  buyer-api/test/routes/health.test.js
  buyer-api/test/setup.js
  buyer-api/test/utils/blockchain.mock.js
  buyer-api/test/utils/blockchain.test.js
  buyer-api/test/utils/snapshots/blockchain.test.js.md
  buyer-api/test/utils/snapshots/blockchain.test.js.snap
  buyer-api/test/utils/snapshots/storage.test.js.md
  buyer-api/test/utils/snapshots/storage.test.js.snap
  buyer-api/test/utils/storage.mock.js
  buyer-api/test/utils/storage.test.js
Labels: v2.0

#128 Add BatPay ABI in both API and SS
  buyer-api/contracts/BatPay.json
  buyer-signing-service/contracts/BatPay.json
Labels: v2.0

#123 Accumulate Data Responses and trigger the Notarization process
  buyer-api/.env.example
  buyer-api/config/index.js
  buyer-api/src/app.js
  buyer-api/src/operations/addDataResponse.js
  buyer-api/src/queues/dataResponseQueue.js
  buyer-api/src/queues/notarizationQueue.js
  buyer-api/src/routes/dataOrders/addDataResponse.js
  buyer-api/src/routes/dataResponses.js
  buyer-api/src/routes/index.js
  buyer-api/src/utils/storage.js
  buyer-api/src/utils/stores.js
  buyer-api/test/operations/snapshots/addDataResponse.test.js.md
  buyer-api/test/operations/snapshots/addDataResponse.test.js.snap
  buyer-api/test/queues/dataResponseQueue.mock.js
  buyer-api/test/queues/dataResponseQueue.test.js
  buyer-api/test/queues/snapshots/dataResponseQueue.test.js.md
  buyer-api/test/queues/snapshots/dataResponseQueue.test.js.snap
Labels: enhancement, v2.0

#126 v2 create data order e2e
  buyer-api/.eslintrc.js
  buyer-api/e2e/operations/createDataOrder.e2e.js
  buyer-api/e2e/operations/createDataOrder.mock.js
  buyer-api/package.json
  buyer-api/src/routes/dataOrders/createDataOrder.js
Labels: enhancement, v2.0

#124 Endpoint to receive notarization results in BAPI
  buyer-api/package-lock.json
  buyer-api/src/app.js
  buyer-api/src/facades/index.js
  buyer-api/src/facades/notariesFacade.js
  buyer-api/src/operations/notarizationResultReception.js
  buyer-api/src/routes/notarizationResult.js
  buyer-api/src/utils/index.js
  buyer-api/src/utils/routes.js
  buyer-api/src/utils/stores.js
  buyer-api/test/operations/notarizationResultReception.fixture.js
  buyer-api/test/operations/notarizationResultReception.mock.js
  buyer-api/test/operations/notarizationResultReception.test.js
  buyer-api/test/operations/snapshots/notarizationResultReception.test.js.md
  buyer-api/test/operations/snapshots/notarizationResultReception.test.js.snap
Labels: v2.0

#131 Sign BatPay.transfer transactions
  buyer-signing-service/.env.example
  buyer-signing-service/config/index.js
  buyer-signing-service/src/contracts/index.js
  buyer-signing-service/src/helpers/buildMethodSigner.js
  buyer-signing-service/src/routes/sign/batPayTransfer.js
  buyer-signing-service/src/routes/sign/index.js
  buyer-signing-service/test/routes/sign/batPayTransferSpec.js
  buyer-signing-service/test/routes/sign/closeDataOrderSpec.js
  buyer-signing-service/test/routes/sign/createDataOrderSpec.js
Labels: v2.0

#129 add titles to test snapshots
  buyer-api/test/operations/addDataResponse.test.js
  buyer-api/test/operations/createDataOrder.test.js
  buyer-api/test/operations/snapshots/addDataResponse.test.js.md
  buyer-api/test/operations/snapshots/addDataResponse.test.js.snap
  buyer-api/test/operations/snapshots/createDataOrder.test.js.md
  buyer-api/test/operations/snapshots/createDataOrder.test.js.snap
  buyer-api/test/queues/dataResponseQueue.test.js
  buyer-api/test/queues/snapshots/dataResponseQueue.test.js.md
  buyer-api/test/queues/snapshots/dataResponseQueue.test.js.snap
  buyer-api/test/utils/blockchain.test.js
  buyer-api/test/utils/snapshots/blockchain.test.js.md
  buyer-api/test/utils/snapshots/blockchain.test.js.snap
  buyer-api/test/utils/snapshots/storage.test.js.md
  buyer-api/test/utils/snapshots/storage.test.js.snap
  buyer-api/test/utils/storage.test.js
Labels: enhancement, v2.0

#134 fix notarization-result endpoint
  buyer-api/src/routes/index.js
  buyer-api/src/routes/notarizationResult.js
Labels: bug

#130 Prepare the NotarizationRequest
  buyer-api/.env.example
  buyer-api/config/index.js
  buyer-api/src/operations/createDataOrder.js
  buyer-api/src/queues/notarizationQueue.js
  buyer-api/src/utils/stores.js
  buyer-api/test/queues/notarizationQueue.mock.js
  buyer-api/test/queues/notarizationQueue.test.js
  buyer-api/test/queues/snapshots/notarizationQueue.test.js.md
  buyer-api/test/queues/snapshots/notarizationQueue.test.js.snap
Labels: v2.0

#132 Send NotarizationRequest to the Notary's API
  buyer-api/src/facades/index.js
  buyer-api/src/facades/notariesFacade.js
  buyer-api/src/queues/notarizationQueue.js
  buyer-api/src/services/notaryService.js
  buyer-api/src/utils/storage.js
  buyer-api/src/utils/stores.js
  buyer-api/test/queues/notarizationQueue.mock.js
  buyer-api/test/queues/notarizationQueue.test.js
  buyer-api/test/queues/snapshots/notarizationQueue.test.js.md
  buyer-api/test/queues/snapshots/notarizationQueue.test.js.snap
Labels: v2.0

#137 Integrate Notarization request and result
  buyer-api/package-lock.json
  buyer-api/src/app.js
  buyer-api/src/facades/notariesFacade.js
  buyer-api/src/operations/addDataResponse.js
  buyer-api/src/operations/receiveNotarizationResult.js
  buyer-api/src/queues/dataResponseQueue.js
  buyer-api/src/queues/notarizationQueue.js
  buyer-api/src/queues/tranferNotarizationResultQueue.js
  buyer-api/src/services/notaryService.js
  buyer-api/src/services/signingService.js
  buyer-api/src/utils/blockchain.js
  buyer-api/src/utils/stores.js
  buyer-api/test/operations/addDataResponse.test.js
  buyer-api/test/operations/notaryService.fixture.js
  buyer-api/test/operations/notaryService.mock.js
  buyer-api/test/operations/notaryService.test.js
  buyer-api/test/operations/receiveNotarizationResult.mock.js
  buyer-api/test/operations/receiveNotarizationResult.test.js
  buyer-api/test/operations/snapshots/addDataResponse.test.js.md
  buyer-api/test/operations/snapshots/addDataResponse.test.js.snap
  buyer-api/test/operations/snapshots/notaryService.test.js.md
  buyer-api/test/operations/snapshots/notaryService.test.js.snap
  buyer-api/test/operations/snapshots/receiveNotarizationResult.test.js.md
  buyer-api/test/operations/snapshots/receiveNotarizationResult.test.js.snap
  buyer-api/test/queues/dataResponseQueue.test.js
  buyer-api/test/queues/notarizationQueue.test.js
  buyer-api/test/queues/snapshots/dataResponseQueue.test.js.md
  buyer-api/test/queues/snapshots/dataResponseQueue.test.js.snap
  buyer-api/test/queues/snapshots/notarizationQueue.test.js.md
  buyer-api/test/queues/snapshots/notarizationQueue.test.js.snap
  buyer-api/test/services/notaryService.mock.js
  buyer-api/test/services/notaryService.test.js
  buyer-api/test/services/snapshots/notaryService.test.js.md
  buyer-api/test/services/snapshots/notaryService.test.js.snap
  buyer-api/test/utils/blockchain.mock.js
Labels: v2.0

#140 refactor blockchain
  buyer-api/.env.example
  buyer-api/config/index.js
  buyer-api/src/blockchain/balance.js
  buyer-api/src/blockchain/contractEventListener.js
  buyer-api/src/blockchain/contracts.js
  buyer-api/src/blockchain/dataOrder.js
  buyer-api/src/blockchain/utils.js
  buyer-api/src/contractEvents/dataOrderSubscriber.js
  buyer-api/src/contractEvents/index.js
  buyer-api/src/contractEvents/listenContractEvents.js
  buyer-api/src/contractEvents/notarySubscriber.js
  buyer-api/src/queues/transactionQueue.js
  buyer-api/src/server.js
  buyer-api/test/blockchain/dataOrder.mock.js
  buyer-api/test/blockchain/dataOrder.test.ignore.js
  buyer-api/test/contractEvents/dataOrderSubscriber.test.js
  buyer-api/test/operations/enqueueDataResponse.test.js
Labels: enhancement, v2.0

#135 level performance test
  buyer-api/package.json
  buyer-api/src/blockchain/contracts.js
  buyer-api/src/utils/storage.js
  buyer-api/test/setup.js
  buyer-api/test/utils/storage.level.performance.test.js
  buyer-api/test/utils/storage.mock.js
  buyer-api/test/utils/storage.test.js
Labels: enhancement

#143 Update createDataOrder snapshot
  buyer-api/test/operations/snapshots/createDataOrder.test.js.md
  buyer-api/test/operations/snapshots/createDataOrder.test.js.snap
Labels: bug, v2.0

#144 save tx hash on order creation
  buyer-api/package-lock.json
  buyer-api/package.json
  buyer-api/src/blockchain/batPay.js
  buyer-api/src/blockchain/contractEventListener.js
  buyer-api/src/blockchain/contractEventSubscribers.js
  buyer-api/src/blockchain/contracts.js
  buyer-api/src/blockchain/dataOrder.js
  buyer-api/src/blockchain/utils.js
  buyer-api/src/server.js
  buyer-api/src/services/notaryService.js
  buyer-api/test/operations/notaryService.fixture.js
  buyer-api/test/operations/notaryService.mock.js
  buyer-api/test/operations/snapshots/notaryService.test.js.md
  buyer-api/test/operations/snapshots/notaryService.test.js.snap
  buyer-api/test/utils/blockchain.test.ignore.js
Labels: v2.0

#145 save tx hash on order creation [cleanup]
  buyer-api/src/blockchain/balance.js
  buyer-api/src/facades/closeDataOrderFacade.js
  buyer-api/src/facades/helpers/blockchain.js
  buyer-api/src/facades/helpers/date.js
  buyer-api/src/facades/helpers/index.js
  buyer-api/src/facades/sellersFacade.js
  buyer-api/src/queues/retryFailed.js
  buyer-api/src/routes/account.js
  buyer-api/src/utils/blockchain.js
  buyer-api/src/utils/contracts.js
  buyer-api/src/utils/index.js
  buyer-api/test/utils/blockchain.test.ignore.js
Labels: enhancement, v2.0

#150 Update Babel 7
  buyer-api/.babelrc
  buyer-api/babel.config.js
  buyer-api/package-lock.json
  buyer-api/package.json
  buyer-api/src/index.js
  buyer-api/src/server.js
  buyer-api/src/tasks/index.js
  buyer-api/test/operations/receiveNotarizationResult.test.js
  buyer-api/test/operations/snapshots/addDataResponse.test.js.snap
  buyer-api/test/operations/snapshots/createDataOrder.test.js.snap
  buyer-api/test/operations/snapshots/notaryService.test.js.snap
  buyer-api/test/operations/snapshots/receiveNotarizationResult.test.js.snap
  buyer-api/test/queues/snapshots/dataResponseQueue.test.js.md
  buyer-api/test/queues/snapshots/dataResponseQueue.test.js.snap
  buyer-api/test/queues/snapshots/notarizationQueue.test.js.snap
  buyer-api/test/utils/blockchain.test.ignore.js
  buyer-api/test/utils/snapshots/blockchain.test.js.md
  buyer-api/test/utils/snapshots/blockchain.test.js.snap
  buyer-api/test/utils/snapshots/storage.test.js.md
  buyer-api/test/utils/snapshots/storage.test.js.snap
  buyer-signing-service/.babelrc
  buyer-signing-service/babel.config.js
  buyer-signing-service/package-lock.json
  buyer-signing-service/package.json
  buyer-signing-service/scripts/test.sh
  buyer-signing-service/src/index.js
  buyer-signing-service/src/server.js
Labels: enhancement, v2.0
